foreground: "#b5c1cb"   #shadow200
details: "darker"
background:
  top: "#13232e"        #twilight900
  bottom: "#0f141c"     #shadow900
accent:
  left: "#9d46c2"       #dusk700
  right: "#17bbe6"      #twilight100
terminal_colors:
  bright:
    black: "#5e6c80"    #shadow500
    blue: "#1a78de"     #pool100
    cyan: "#17bbe6"     #twilight100
    green: "#41db5e"    #shade100
    magenta: "#a949da"  #dusk100
    red: "#e55b9a"      #dawn100
    white: "#eaeef0"    #shadow050
    yellow: "#dfcd19"   #sun050
  normal:
    black: "#313c4e"    #shadow700
    blue: "#2556af"     #pool300
    cyan: "#218ab8"     #twilight300
    green: "#3dad5a"    #shade300
    magenta: "#8e41aa"  #dusk300
    red: "#bc4764"      #dawn300
    white: "#b5c1cb"    #shadow200
    yellow: "#beb21b"   #sun300
