foreground: "#c2c7cc"   #shadow200
details: "earthy"
background:
  top: "#2f333a"        #twilight900
  bottom: "#1a1d21"     #shadow900
accent:
  left: "#a38eaa"       #dusk700
  right: "#8caab8"      #twilight050
terminal_colors:
  bright:
    black: "#737a83"    #shadow500
    blue: "#d3dfe9"     #pool100
    cyan: "#c8e0e6"     #twilight100
    green: "#cfdbd2"    #shade100
    magenta: "#d3cbd7"  #dusk100
    red: "#e5d3db"      #dawn100
    white: "#edeff0"    #shadow050
    yellow: "#f7e6bc"   #sun050
  normal:
    black: "#454a52"    #shadow700
    blue: "#8a97af"     #pool300
    cyan: "#8caab8"     #twilight300
    green: "#91ad98"    #shade300
    magenta: "#a38eaa"  #dusk300
    red: "#bc8e99"      #dawn300
    white: "#c2c7cc"    #shadow200
    yellow: "#cdbb80"   #sun300
