background:   "#222c35"
accent:
  left:       "#74c8a9"
  right:      "#d68ac0"
foreground:   "#ced5c4"
details: darker
terminal_colors:
  normal:
    black:    "#373c44"
    red:      "#d86575"
    green:    "#86b981"
    yellow:   "#dbbe7a"
    blue:     "#79b7c9"
    magenta:  "#b189d6"
    cyan:     "#74c8a9"
    white:    "#d9d5c4"
  bright:
    black:    "#555960"
    red:      "#de7c8a"
    green:    "#92c08e"
    yellow:   "#e0c88e"
    blue:     "#8dc2d1"
    magenta:  "#c8ace2"
    cyan:     "#89d0b6"
    white:    "#dfdbcd"

