background:   "#283038"
accent:
  left:       "#7bc29a"
  right:      "#d491b5"
foreground:   "#d0c9a1"
details: darker
terminal_colors:
  normal:
    black:    "#374149"
    red:      "#da7280"
    green:    "#a8c180"
    yellow:   "#dbba79"
    blue:     "#78b1bd"
    magenta:  "#d491b5"
    cyan:     "#7bc29a"
    white:    "#d0c9a1"
  bright:
    black:    "#526564"
    red:      "#da7280"
    green:    "#a8c180"
    yellow:   "#dbba79"
    blue:     "#78b1bd"
    magenta:  "#d491b5"
    cyan:     "#7bc29a"
    white:    "#f8f7f2"

