background:   "#283038"
accent:
  left:       "#7bc29a"
  right:      "#d491b5"
foreground:   "#cfc2a4"
details: darker
terminal_colors:
  normal:
    black:    "#374149"
    magenta:  "#d694be"
    red:      "#da7280"
    yellow:   "#dbba79"
    green:    "#a8c180"
    cyan:     "#7bc29a"
    blue:     "#78b1bd"
    white:    "#cfc2a4"
  bright:
    black:    "#526564"
    red:      "#f1949c"
    green:    "#b6d881"
    yellow:   "#fae2b2"
    blue:     "#95dae8"
    magenta:  "#fdade4"
    cyan:     "#89e5be"
    white:    "#e5d9bc"

