authtoken: ***REMOVED***
connect_timeout: 30s
console_ui: true
console_ui_color: transparent

log_level: info
log_format: json
log: stdout
region: us
update_check: false
version: 2
tunnels:
  swmlive:
    addr: "api.swbuildnet.com"
    schemes:
      - https
    host_header: "swbuildnet.com"
    proto: https
