authtoken: ***REMOVED***
connect_timeout: 30s
console_ui: true
console_ui_color: transparent

log_level: info
log_format: json
log: false
region: us
update_check: false
version: 2
tunnels:
  swmlocal:
    addr: localhost:5003
    schemes:
      - https
    proto: http
    response_header:
      add:
        - "Access-Control-Allow-Origin:*"
        - "Access-Control-Allow-Headers:*"
