black: "#393b44"
red: "#c94f6d"
red-dim: "#2f2837"
green: "#81b29a"
green-dim: "#26343c"
yellow: "#dbc074"
yellow-bright: "#e0c989"
blue: "#719cd6"
blue-bright: "#86abdc"
blue-dim: "#2f2837"
magenta: "#9d79d6"
magenta-bright: "#baa1e2"
cyan: "#63cdcf"
cyan-bright: "#7ad4d6"
cyan-dim: "#253f4a"
white: "#dfdfe0"
orange: "#f4a261"
orange-bright: "#f6b079"
pink: "#d67ad2"
pink-bright: "#dc8ed9"
comment: "#738091"
bg0: "#131a24"
bg1: "#192330"
bg2: "#212e3f"
bg3: "#29394f"
bg4: "#39506d"
fg0: "#d6d6d7"
fg1: "#cdcecf"
fg2: "#aeafb0"
fg3: "#71839b"
sel0: "#2b3b51"
sel1: "#3c5372"


background: ""
accent:
  left: "#007972"
  right: "#7b008f"
foreground: "#ffffff"
details: darker
terminal_colors:
  normal:
    black: "#616161"
    red: "#ff8272"
    green: "#b4fa72"
    yellow: "#fefdc2"
    blue: "#a5d5fe"
    magenta: "#ff8ffd"
    cyan: "#d0d1fe"
    white: "#f1f1f1"
  bright:
    black: "#8e8e8e"
    red: "#ffc4bd"
    green: "#d6fcb9"
    yellow: "#fefdd5"
    blue: "#c1e3fe"
    magenta: "#ffb1fe"
    cyan: "#e5e6fe"
    white: "#feffff"