background: "#192330"
accent:
  left: "#63cdcf"
  right: "#dc8ed9"
foreground: "#d6d6d7"
details: darker
terminal_colors:
  normal:
    black: "#393b44"
    red: "#c94f6d"
    green: "#81b29a"
    yellow: "#dbc074"
    blue: "#719cd6"
    magenta: "#9d79d6"
    cyan: "#63cdcf"
    white: "#dfdfe0"
  bright:
    black: "#738091"
    red: "#cf637d"
    green: "#94b8a7"
    yellow: "#e0c989"
    blue: "#86abdc"
    magenta: "#baa1e2"
    cyan: "#7ad4d6"
    white: "#efeff0"
