foreground: "#ECEFF4"   # 
details: "darker"
background:
  top: "#3B4252"        # 2
  bottom: "#2E3440"     # 1
accent:
  left: "#BF616A"       # 12
  right: "#81A1C1"      # 10
terminal_colors:
  bright:
    black: "#434C5E"    # 3
    blue: "#81A1C1"     # 10
    cyan: "#8FBCBB"     # 8
    green: "#A3BE8C"    # 15
    magenta: "#B48EAD"  #
    red: "#BF616A"      #
    white: "#ECEFF4"    #
    yellow: "#EBCB8B"   #
  normal:
    black: "#3B4252"    #
    blue: "#5E81AC"     #
    cyan: "#88C0D0"     # 9
    green: "#A3BE8C"    # 15
    magenta: "#B48EAD"  #
    red: "#BF616A"      #
    white: "#D8DEE9"    #
    yellow: "#EBCB8B"   #
