command_timeout = 1000
format = """
[](color_bg2)\
$os\
$hostname\
$username\
[](bg:color_bg4 fg:color_bg2)\
$directory\
[](fg:color_bg4 bg:color_grey0)\
$git_branch\
$git_status\
[](fg:color_grey0 bg:color_grey2)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$haskell\
$python\
[](fg:color_grey2 bg:color_grey3)\
$docker_context\
$conda\
[](fg:color_grey3 bg:color_fg0)\
$time\
[ ](fg:color_fg0)\
$line_break$character"""

palette = 'forestfox'

# palette
[palettes.forestfox]
color_bgx = '#232b2e'
color_bg0 = '#283038'
color_bg1 = '#2e373f'
color_bg2 = '#374149'
color_bg3 = '#404b54'
color_bg4 = '#48565c'
color_bg5 = '#526465'
color_grey0 = '#778378'
color_grey1 = '#869388'
color_grey2 = '#9da99e'
color_grey3 = '#b2b6a7'
color_fg0 = '#c3bda3'
color_fg1 = '#cfc2a4'
color_fg2 = '#e5d9bc'
color_blue = '#5c7d8e'
color_aqua = '#5a8b7f'
color_green = '#678b65'
color_orange = '#af7852'
color_magenta = '#96668c'
color_red = '#965e67'
color_yellow = '#857d57'
# end palette 

[os]
disabled = false
style = "bg:color_bg2 fg:white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[hostname]
ssh_only = false
disabled = false
format = "[  $hostname::](bg:color_bg2 fg:green)"

[username]
show_always = true
format = '[$user ](bg:color_bg2 fg:white)'

[directory]
format = "[ $path ](fg:white bg:color_bg4)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙  "
"Downloads" = "  "
"Music" = "󰝚  "
"Pictures" = "  "

[git_branch]
symbol = ""
style = "bg:color_grey0"
format = '[ $symbol $branch ](fg:white bg:color_grey0)'

[git_status]
format = '[($all_status$ahead_behind )](fg:white bg:color_grey0)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[c]
symbol = " "
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)]'

[rust]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[golang]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[php]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[java]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[kotlin]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[haskell]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[python]
symbol = ""
style = "bg:color_grey2"
format = '[ $symbol( $version) ](fg:color_bg5 bg:color_grey2)'

[docker_context]
symbol = ""
style = "bg:color_grey3"
format = '[ $symbol( $context) ](fg:#83a598 bg:color_grey3)'

[conda]
style = "bg:color_bg5"
format = '[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_fg0"
format = '[  $time ](fg:color_bg5 bg:color_fg0)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ❯](bold fg:color_blue)'
error_symbol = '[ ❯](bold fg:color_red)'
vimcmd_symbol = '[ ❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_magenta)'
vimcmd_replace_symbol = '[❮](bold fg:color_magenta)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
