name: swm
root: ~/dev/bn-modern
windows:
  - editor:
    - cd srapp
    - run node-launch.sh
    - nvim .
  - vue-server:
      pre: cd srapp
      panes:
      - pnpm run test
      - pnpm run dev
  - dotnet:
    - cd API
    - dotnet run
  - docker:
    - docker start --attach swm
  - ngrok:
    - ngrok http https://localhost:5003 --response-header-add "Access-Control-Allow-Origin: *" --response-header-add "Access-Control-Allow-Headers: *"' Er
