# symlinks for various dotfiles
# the target paths are all relative to the HOME directory
[[dotfiles]]
source = "./config/synthwave85.json"
target = ".fleet/themes"

[[dotfiles]]
source = "./config/earth.yaml"
target = ".warp/themes/earth.yaml"