# symlinks for various dotfiles
# the target paths are all relative to the HOME directory
[[dotfiles]]
source = "./synthwave85.json"
target = ".fleet/themes"

[[dotfiles]]
source = "./zshrc"
target = ".zshrc"