# symlinks for various dotfiles
version = "1.1"

[[dotfiles]]
source = "dev/dotfiles/config/forestfox.yaml"
target = ".warp/themes/forestfox.yaml"

[[dotfiles]]
source = "dev/dotfiles/config/starship.toml"
target = ".config/starship.toml"

[[dotfiles]]
source = "dev/dotfiles/config/.zshrc"
target = ".config/zsh/.zshrc"

[[dotfiles]]
source = "dev/dotfiles/config/.zprofile"
target = ".zprofile"

[[dotfiles]]
source = "dev/dotfiles/config/wezterm.lua"
target = "wezterm.lua"
win_target = ".config/wezterm/wezterm.lua"

[[dotfiles]]
source = "dev/dotfiles/config/tmux.conf"
target = ".config/tmux/tmux.conf"

[[dotfiles]]
source = "dev/dotfiles/config/config"
target = ".config/ghostty/config"

[[dotfiles]]
source = "dev/dotfiles/config/forestfox"
target = ".config/ghostty/themes/forestfox"

[[dotfiles]]
source = "dev/dotfiles/nvim"
target = ".config/nvim"
win_target = "%LOCALAPPDATA%/nvim"

[[dotfiles]]
source = "dev/dotfiles/bin/netcoredbg"
target = "/usr/local/bin/netcoredbg"

