# symlinks for various dotfiles
# the target paths are all relative to the HOME directory
#[[dotfiles]]
#source = "../config/synthwave85.json"
#target = ".fleet/themes"

[[dotfiles]]
source = "../config/nightfox.yaml"
target_dir = ".warp/themes"
target_file = "nightfox.yaml"

[[dotfiles]]
source = "../config/forestfox.yaml"
target_dir = ".warp/themes"
target_file = "forestfox.yaml"

[[dotfiles]]
source = "../config/nord.yaml"
target_dir = ".warp/themes"
target_file = "nord.yaml"

[[dotfiles]]
source = "../config/.zshrc"
target_dir = ""
target_file = ".zshrc"
