# symlinks for various dotfiles
# the target paths are all relative to the HOME directory

[[dotfiles]]
source = "../config/nightfox.yaml"
target = ".warp/themes/nightfox.yaml"

[[dotfiles]]
source = "../config/forestfox.yaml"
target = ".warp/themes/forestfox.yaml"

[[dotfiles]]
source = "../config/nord.yaml"
target = ".warp/themes/nord.yaml"

[[dotfiles]]
source = "../config/starship.toml"
target = ".config/starship.toml"

[[dotfiles]]
source = "../config/.zshrc"
target = ".zshrc"

[[dotfiles]]
source = "../nvim"
target = ".config/nvim"

